In [7]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris, load_diabetes, load_breast_cancer, load_wine
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.svm import SVC

# Load the Iris dataset
# dataset = load_iris()
#dataset = load_diabetes()
# dataset = load_breast_cancer()
dataset = load_wine()
df = dataset.data
y = dataset.target

# Split the dataset into training and testing sets - Hold Out Method
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.4, random_state=42)

svc = SVC(kernel='linear', C=1.0, random_state=42)
svc.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svc.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{cm}")

print(f"Classification Report:\n{classification_report(y_test, y_pred)}")

Accuracy: 0.9444444444444444
Confusion Matrix:
[[26  0  0]
 [ 4 23  0]
 [ 0  0 19]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        26
           1       1.00      0.85      0.92        27
           2       1.00      1.00      1.00        19

    accuracy                           0.94        72
   macro avg       0.96      0.95      0.95        72
weighted avg       0.95      0.94      0.94        72

