Numpy Library for Matrix operations

In [3]:
import numpy as np

arrobj01 = np.array([1,2,3,4])
print(arrobj01)

#arrobj2 = np.array([12,"Hi","Welcome",34,56], dtype=int)#error for String values
#print(arrobj2)

#Two Dimension
arrobj2 = np.array([[1,2,3],[4,5,6],[8,7,9]], dtype=int)
print("Size", arrobj2.size)
print(arrobj2.ctypes)
#Attributes of Matrix
print("Dimensions", arrobj2.ndim)
print("shape",arrobj2.shape)

#single Dimension
arrobj3 = np.array([1,2,3,4,5,6,7], dtype=int)
print("Dimensions", arrobj3.ndim)
print("shape",arrobj3.shape)

#Three Dimension
arrobj4 = np.array([[[1,2], [3,4]], [[5,6],[7,8]], [[9,10], [11,12]]])
print("Dimensions", arrobj4.ndim)
print("shape",arrobj4.shape)

[1 2 3 4]
Size 9
Dimensions 2
shape (3, 3)
Dimensions 1
shape (7,)
Dimensions 3
shape (3, 2, 2)


In [4]:
import numpy as np

arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

print("First Row",arr[0])
print("First Row, Second column", arr[0][1])

arr2 = arr[:2, ::2]
print("First 2 rows and alternate columns:\n", arr2)

arr3 = arr[[1, 1, 0, 3], [3, 2, 1, 0]]
print("Selected elements:", arr3)

First Row [-1.  2.  0.  4.]
First Row, Second column 2.0
First 2 rows and alternate columns:
 [[-1.  0.]
 [ 4.  6.]]
Selected elements: [0. 6. 2. 3.]


In [5]:
#Arithmetic operators with Arrays
arrobj1 = np.array([
            [1, 2],
            [3, 4]])
arrobj2 = np.array([
            [5, 6],
            [7, 8]])
#Basic arithmetic operators with arrays
print(arrobj1+1)
arrobj3 = arrobj1 + arrobj2

print(np.add(arrobj1, arrobj2))
print(arrobj3)

print(arrobj2.sum())

print(arrobj3 - 2)
print(arrobj3.dtype)

print(arrobj1 * arrobj2)
print(arrobj1 / arrobj2)

[[2 3]
 [4 5]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
26
[[ 4  6]
 [ 8 10]]
int64
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [6]:
#print(np.sqrt(arrobj2))
#print(arrobj2.T)#Transpose of Matrix

res = np.dot(arrobj1, arrobj2)
print(res)

[[19 22]
 [43 50]]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#convert from 1D to 2D
newarr = arr.reshape(4, 3)
#print(newarr)
#convert from 2D to 1D
arr2 = newarr.reshape(12,)
#print(arr2)

newarr3D = arr.reshape(2, 3, 2)
print(newarr3D)

newarr = arr.reshape(-1)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print("Concatenate : ",arr)

arr = np.stack((arr1, arr2), axis=1)
print("stack : ",arr)

arr = np.hstack((arr1, arr2))
print("Horizontal Stack : ",arr)

arr = np.vstack((arr1, arr2))
print("Vertical Stack : ", arr)

arr = np.dstack((arr1, arr2))
print("Depth Stack : ", arr)

Concatenate :  [1 2 3 4 5 6]
stack :  [[1 4]
 [2 5]
 [3 6]]
Horizontal Stack :  [1 2 3 4 5 6]
Vertical Stack :  [[1 2 3]
 [4 5 6]]
Depth Stack :  [[[1 4]
  [2 5]
  [3 6]]]


In [13]:
#Split methods
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

for arr1 in newarr:
    print(arr1)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

for arr1 in newarr:
    print(arr1)

[1 2]
[3 4]
[5 6]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [17]:
#searching
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 1)
print(x)

arr = np.array([10, 14, 93, 41, 8, 7])
x = np.where(arr%2 == 1)
print(x)

(array([0]),)
(array([2, 3, 5]),)


In [24]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

np.arange(10, 100, 5)

[0 1 2 3]
['apple' 'banana' 'cherry']


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [20]:
c = np.array([[1, 2], [3, 4]], dtype=np.complex128)
np.array([[1.+0.j, 2.+0.j],[3.+0.j, 4.+0.j]])

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
np.zeros((3, 4))
np.ones((2, 3, 4), dtype=np.int16)

a = np.random.default_rng(4)
a.random((2,3))

arr1.fill(0)
print(arr1)
arr2 = arr1.flatten()
print(arr2)
listobj = arr1.tolist()
print(listobj)


[[0 0]
 [0 0]]
[0 0 0 0]
[[0, 0], [0, 0]]


In [ ]:
# Create a 2-D array with elements initialized to 5 
numpy_array = np.full((2, 2), 5)

print("Array:", numpy_array)
np.array((2,3),dtype=np.in)

Array: [[5 5]
 [5 5]]


In [37]:
import time

# Loop - based operation
my_list = list(range(1000000))
start_time_loop = time.time()
result_loop = []
for num in my_list:
    result_loop.append(num * 2)
end_time_loop = time.time()
loop_time = end_time_loop - start_time_loop

# Vectorized operation
my_array = np.array(my_list)
start_time_vectorized = time.time()
result_vectorized = my_array * 2
end_time_vectorized = time.time()
vectorized_time = end_time_vectorized - start_time_vectorized

print(f"Time taken by loop: {loop_time} seconds")
print(f"Time taken by vectorized operation: {vectorized_time} seconds")

Time taken by loop: 0.06942439079284668 seconds
Time taken by vectorized operation: 0.0020062923431396484 seconds
