In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv('sms_spam_dataset.csv', encoding='ISO-8859-1').iloc[:,0:2]

# Data overview
print("DataFrame Head:")
print(df.head())
print("\nDataFrame Info:")
print(df.info())

## Applying TF-IDF Vectorizer
# Initialize the TF-IDF vectorizer, removing stopwords and numbers
tfidf_vectorizer = TfidfVectorizer(stop_words='english', 
                                     token_pattern=r'\b[a-zA-Z]+\b')  # Only keep alphabetic words

# Fit and transform the message column (v2) to create the TF-IDF matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(df['v2'])

# Convert the TF-IDF matrix to a DataFrame for better visualization
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

# Display the TF-IDF DataFrame
print("\nTF-IDF DataFrame:")
tfidf_df

X = tfidf_matrix
y = df['v1'].map({'ham': 0, 'spam': 1})  # Encoding labels as 0 for ham and 1 for spam

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.naive_bayes import CategoricalNB, GaussianNB, MultinomialNB, ComplementNB, BernoulliNB

#other options for Naive Byes include GaussianNB, BernoulliNB, ComplementNB, CategoricalNB, etc. depending on the nature of the data and the problem at hand.
#nb_model = BernoulliNB()  # For binary/boolean features
#nb_model = ComplementNB()  # For imbalanced data
nb_model = MultinomialNB()  # Multinomial Naive Bayes is typically used for text classification tasks
#nb_model = CategoricalNB()  # For categorical features
nb_model.fit(X_train, y_train)

y_train_pred = nb_model.predict(X_train)
y_test_pred = nb_model.predict(X_test)

print("Confusion Matrix: Train Data")
print(confusion_matrix(y_train, y_train_pred))
print("\nClassification Report (Train Data):")
print(classification_report(y_train, y_train_pred))
print("============================================================================")

# Evaluate the model on test data
print("Confusion Matrix: Test Data")
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification Report (Test Data):")
print(classification_report(y_test, y_test_pred))


new_data = pd.DataFrame([["How are you doing? Did you finish your work?"],['Nice weather! Lets go for a walk.'],['Free! Free! Absolutely free!']],columns=['v2'])


new_data_vector = tfidf_vectorizer.transform(new_data['v2'])

nb_model.predict(new_data_vector)

DataFrame Head:
    v1                      v2
0  ham  See you at the office.
1  ham  See you at the office.
2  ham          Lunch at 1 PM?
3  ham          Lunch at 1 PM?
4  ham          Lunch at 1 PM?

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      1000 non-null   object
 1   v2      1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB
None

TF-IDF DataFrame:
Confusion Matrix: Train Data
[[638   0]
 [  0 162]]

Classification Report (Train Data):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       638
           1       1.00      1.00      1.00       162

    accuracy                           1.00       800
   macro avg       1.00      1.00      1.00       800
weighted avg       1.00      1.00      1.00       800

Confusion Matrix: Test Data
[[162   0]
 [  0  38]]


array([0, 0, 1])